name: loans
description: Loans application
publish_to: none
version: 0.0.1+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Modules
  core:
    path: modules/core
  api:
    path: modules/api
