name: loans
description: Loans application
publish_to: none
version: 0.0.1+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Modules
  core:
    path: modules/core
  firebase_api:
    path: modules/firebase_api
  ui_kit:
    path: modules/ui_kit

  # Navigation
  go_router: 10.0.0

  # State management
  bloc: 8.1.2
  flutter_bloc: 8.1.3

  # Localization
  intl: 0.18.0
  flutter_localizations:
    sdk: flutter

  # Logging
  mark: 0.3.0

  # UI
  mask_text_input_formatter: 2.5.0

  # Utils
  meta: 1.9.1
  rxdart: 0.27.7
  collection: 1.17.1
  firebase_core: 2.15.0
  bloc_concurrency: 0.2.2

dev_dependencies:
  # Code generation
  build_runner: 2.4.6
  build_verify: 3.1.0

  # Utils
  flutter_gen_runner: 5.3.1

flutter_gen:
  output: lib/src/shared/assets/

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets\fonts\Inter-ExtraBold.ttf
          weight: 800
        - asset: assets\fonts\Inter-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Inter-Medium.ttf
          weight: 500

    - family: Icons
      fonts:
        - asset: assets\fonts\icons.ttf
