name: loans
description: Loans application
publish_to: none
version: 0.0.1+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Modules
  core:
    path: modules/core
  api:
    path: modules/api

  # Navigation
  go_router: 10.0.0

  # State management
  bloc: 8.1.2
  flutter_bloc: 8.1.3

  # Utils
  meta: 1.9.1
  rxdart: 0.27.7
  collection: 1.17.1
  firebase_core: 2.15.0
  bloc_concurrency: 0.2.2
