name: ui_kit
description: Application UI kit.
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utils
  theme_tailor_annotation: 2.0.0

dev_dependencies:
  # Code generation
  build_runner: 2.4.6
  build_verify: 3.1.0
  theme_tailor: 2.0.0
